<?php
$lang = array(
"anasayfa"		=> "Anasayfa",
"anasayfa-light" =>"Anasayfa - Açık",
"anasayfa-dark" =>"Anasayfa - Koyu",
"blogyazi"	        => "Blog Yazıları",
"detailsyazi"	        => "Blog Details Yazıları",
"bloglar"	        => "Blog",
"bloglist"	        => "Blog - Liste",
"blogpost"	        => "Blog - İleti",
"details"	        => "Blog Detay",
"trdil"			=> "Türkçe",
"ingdil"		=> "İngilizce",
"hakkimizda"		=> "Hakkımızda",
"project"			=> "Projeler",
"project-list"			=> "Proje - Liste",
"project-details"			=> "Proje - Detay",
"renkler"	        => "Renkler",
"panel"			=> "Yönetici Paneli",
"cikis"	        => "Çıkış Yap",
"okunmamismesaj"		=> "Okunmamış Mesaj",
"detaygor"			=> "Detay Gör",
"search"			=> "Ara",
"ekle"		=> "Yeni Ekle",
"dil"		=> "Dil Seçin",
"baslik"		=> "Başlık",
"altbaslik"		=> "Alt Başlık",
"aciklama"    =>"Açıklama",
"temizle"   =>"Temizle",
"kaydet"  =>"Submit",
"tarih"			=> "Tarih",
"aktif"		=> "Aktif",
"pasif"  => " Pasif",
"arac"     =>"Araç",
"update"   => "Düzenle",
"don" => "Geri Dön",
"our" => "Dış",
"services" => "ayarlar",
"biz" => "Biz",
"dunya" => "Dünya Çapında",
"get" => "bizimle",
"iletisim" =>"iletişim kurunuz",
"ad" => "İsim",
"email" => "mail",
"telefon" => "telefon",
"sirket" => "Şirket",
"mesaj" => "mesaj",
"protected" => " Korumalı",
"gonder" =>"Gönder",
"alert" => "Bizimle iletişime geçtiğiniz için teşekkürler",
"hakkimizdabaslik"=>"ARCH HAKKINDA",
"hakkimizdaaltbaslik"=>"fikirleri sanat eserine dönüştürüyoruz..",



);
?>